; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
lib_deps = 
	m5stack/M5Unified
	bblanchon/ArduinoJson@^7.2.2
	m5stack/M5CoreS3@^1.0.1
	https://github.com/haraisao/m5stack-avatar#dev
	https://github.com/haraisao/stackchan-arduino#dev

lib_ldf_mode = deep
board_build.filesystem = littlefs
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

monitor_dtr = 0
monitor_rts = 0

;upload_port = COM7
